version: '3'

services:
    web:
        build: docker/web/
        ports:
            - "5000:5000"
        volumes:
            - ./src/Web:/app
        environment:
            - DOTNET_USE_POLLING_FILE_WATCHER=1

    devtools:
        build: docker/devtools/
        volumes:
            - ./src/ScheduleMeetupConsole:/app
        depends_on:
            - web
